site_name: LinkedIn Guide
docs_dir: docs
repo_url: https://github.com/cdundon123/linkedin-docs
site_url: https://cdundon123.github.io/linkedin-docs/
edit_uri: edit/main/docs/

plugins:
  - search

theme:
  name: material
  icon:
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - search.suggest
    - content.action.edit
    - content.action.view

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - "LinkedIn overview": index.md
  - "Apply to jobs with LinkedIn": 
    - "Set up your profile": apply/set-up-your-profile.md
    - "Add job preferences": apply/add-job-preferences.md
    - "Search for jobs": apply/search-for-jobs.md
    - "Apply for a job": apply/apply-for-jobs.md
    - "Track application progress": apply/track-application.md
  - "LinkedIn Premium Career features":
    - "What is LinkedIn Premium Career?": premium/index.md
    - "View analytics for a job posting": premium/view-analytics.md
    - "Mark a job as your Top Choice": premium/mark-job-as-top-choice.md
    - "See who has viewed your profile": premium/see-who-viewed-profile.md
    - "Learn with LinkedIn Learning": premium/linkedin-learning.md
    - "Activate Premium Perks": premium/activate-premium-perks.md
  - "References":
    - "Intro and profile fields": references/intro-fields.md
    - "Standard vs Premium Career": references/linkedin-plans.md
    - "Job collections": references/job-collections.md